package pda

import (
	"fmt"
	"testing"
)

func TestPDA_Match(t *testing.T) {
	type inputResults struct {
		input string
		want  bool
	}
	tests := []struct {
		startSymbol  string
		rules        []string
		inputResults []inputResults
	}{
		{
			startSymbol: "S",
			rules: []string{
				"S: a S b",
				"S: !",
			},
			inputResults: []inputResults{
				{input: "ab", want: true},
				{input: "aabb", want: true},
				{input: "aaaabbbb", want: true},
				{input: "ababa", want: false},
				{input: "bbaaa", want: false},
			},
		},
		{
			startSymbol: "S",
			rules: []string{
				"S: b A b",
				"S: a A a",
				"S: a",
				"S: b",
				"A: b A b",
				"A: a A a",
				"A: a",
				"A: b",
				"A: b A a",
				"A: a A b",
				"A: !",
			},
			inputResults: []inputResults{
				{input: "a", want: true},
				{input: "b", want: true},
				{input: "baaababababababbbbbbab", want: true},
				{input: "abbbbbabbbabbbbbbbabba", want: true},
				{input: "babbab", want: true},
				{input: "baaaaba", want: false},
			},
		},
		{
			startSymbol: "S",
			rules: []string{
				"S: a S a",
				"S: b S b",
				"S: !",
			},
			inputResults: []inputResults{
				{input: "abba", want: true},
			},
		},
		{
			startSymbol: "S",
			rules: []string{
				"S: U",
				"S: V",
				"U: T a U",
				"U: T a T",
				"V: T b V",
				"V: T b T",
				"T: a T b T",
				"T: b T a T",
				"T: !",
			},
			inputResults: []inputResults{
				{input: "aab", want: true},
				{input: "bbbbbbbbbbbbbbbbbbbbbbbbbbba", want: true},
				{input: "ababababababb", want: true},
				{input: "aaaaaaaaaabbbbbbbbbbb", want: true},
				{input: "aaaaaaaaaabbbbbbbbbb", want: false},
				{input: "ab", want: false},
			},
		},
		{
			startSymbol: "0",
			rules: []string{
				"0: 4 1 5",
				"1: 2 3 | 3 2",
				"2: 4 4 | 5 5",
				"3: 4 5 | 5 4",
				"4: a",
				"5: b",
			},
			inputResults: []inputResults{
				{input: "ababbb", want: true},
				{input: "bababa", want: false},
				{input: "abbbab", want: true},
				{input: "aaabbb", want: false},
				{input: "aaaabbb", want: false},
			},
		},
		{
			startSymbol: "0",
			rules: []string{
				"42: 9 14 | 10 1",
				"9: 14 27 | 1 26",
				"10: 23 14 | 28 1",
				"1: a",
				"11: 42 31",
				"5: 1 14 | 15 1",
				"19: 14 1 | 14 14",
				"12: 24 14 | 19 1",
				"16: 15 1 | 14 14",
				"31: 14 17 | 1 13",
				"6: 14 14 | 1 14",
				"2: 1 24 | 14 4",
				"0: 8 11",
				"13: 14 3 | 1 12",
				"15: 1 | 14",
				"17: 14 2 | 1 7",
				"23: 25 1 | 22 14",
				"28: 16 1",
				"4: 1 1",
				"20: 14 14 | 1 15",
				"3: 5 14 | 16 1",
				"27: 1 6 | 14 18",
				"14: b",
				"21: 14 1 | 1 14",
				"25: 1 1 | 1 14",
				"22: 14 14",
				"8: 42",
				"26: 14 22 | 1 20",
				"18: 15 15",
				"7: 14 5 | 1 21",
				"24: 14 1",
			},
			inputResults: []inputResults{
				{input: "bbabbbbaabaabba", want: true},
				{input: "ababaaaaaabaaab", want: true},
				{input: "ababaaaaabbbaba", want: true},
				{input: "abbbbbabbbaaaababbaabbbbabababbbabbbbbbabaaaa", want: false},
				{input: "babbbbaabbbbbabbbbbbaabaaabaaa", want: false},
				{input: "aaabbbbbbaaaabaababaabababbabaaabbababababaaa", want: false},
				{input: "bbbbbbbaaaabbbbaaabbabaaa", want: false},
				{input: "bbbababbbbaaaaaaaabbababaaababaabab", want: false},
				{input: "baabbaaaabbaaaababbaababb", want: false},
				{input: "abbbbabbbbaaaababbbbbbaaaababb", want: false},
				{input: "aaaaabbaabaaaaababaa", want: false},
				{input: "aaaabbaaaabbaaa", want: false},
				{input: "aaaabbaabbaaaaaaabbbabbbaaabbaabaaa", want: false},
				{input: "babaaabbbaaabaababbaabababaaab", want: false},
				{input: "aabbbbbaabbbaaaaaabbbbbababaaaaabbaaabba", want: false},
			},
		},
		{
			startSymbol: "0",
			rules: []string{
				"42: 9 14 | 10 1",
				"9: 14 27 | 1 26",
				"10: 23 14 | 28 1",
				"1: a",
				"11: 42 31 | 42 11 31",
				"5: 1 14 | 15 1",
				"19: 14 1 | 14 14",
				"12: 24 14 | 19 1",
				"16: 15 1 | 14 14",
				"31: 14 17 | 1 13",
				"6: 14 14 | 1 14",
				"2: 1 24 | 14 4",
				"0: 8 11",
				"13: 14 3 | 1 12",
				"15: 1 | 14",
				"17: 14 2 | 1 7",
				"23: 25 1 | 22 14",
				"28: 16 1",
				"4: 1 1",
				"20: 14 14 | 1 15",
				"3: 5 14 | 16 1",
				"27: 1 6 | 14 18",
				"14: b",
				"21: 14 1 | 1 14",
				"25: 1 1 | 1 14",
				"22: 14 14",
				"8: 42 | 42 8",
				"26: 14 22 | 1 20",
				"18: 15 15",
				"7: 14 5 | 1 21",
				"24: 14 1",
			},
			inputResults: []inputResults{
				{input: "abbbbbabbbaaaababbaabbbbabababbbabbbbbbabaaaa", want: false},
				{input: "bbabbbbaabaabba", want: true},
				{input: "babbbbaabbbbbabbbbbbaabaaabaaa", want: true},
				{input: "aaabbbbbbaaaabaababaabababbabaaabbababababaaa", want: true},
				{input: "bbbbbbbaaaabbbbaaabbabaaa", want: true},
				{input: "bbbababbbbaaaaaaaabbababaaababaabab", want: true},
				{input: "ababaaaaaabaaab", want: true},
				{input: "ababaaaaabbbaba", want: true},
				{input: "baabbaaaabbaaaababbaababb", want: true},
				{input: "abbbbabbbbaaaababbbbbbaaaababb", want: true},
				{input: "aaaaabbaabaaaaababaa", want: true},
				{input: "aaaabbaaaabbaaa", want: false},
				{input: "aaaabbaabbaaaaaaabbbabbbaaabbaabaaa", want: true},
				{input: "babaaabbbaaabaababbaabababaaab", want: false},
				{input: "aabbbbbaabbbaaaaaabbbbbababaaaaabbaaabba", want: true},
			},
		},
		{
			startSymbol: "0",
			rules: []string{
				"77: 30 112 | 20 13",
				"121: 43 20 | 123 30",
				"42: 57 30 | 101 20",
				"30: a",
				"50: 65 20 | 134 30",
				"37: 89 20 | 43 30",
				"106: 16 30 | 54 20",
				"17: 30 84 | 20 35",
				"129: 89 20 | 96 30",
				"123: 30 30 | 20 95",
				"20: b",
				"115: 20 70 | 30 93",
				"112: 30 90 | 20 123",
				"4: 20 55 | 30 5",
				"72: 20 90 | 30 123",
				"51: 30 20 | 20 95",
				"24: 131 30 | 7 20",
				"94: 121 20 | 15 30",
				"117: 133 30 | 102 20",
				"92: 28 20 | 43 30",
				"70: 87 30 | 96 20",
				"88: 109 20 | 36 30",
				"35: 20 36 | 30 61",
				"96: 30 95 | 20 20",
				"47: 96 20 | 66 30",
				"6: 20 55 | 30 123",
				"130: 30 29 | 20 88",
				"68: 5 20 | 89 30",
				"66: 95 95",
				"75: 96 30 | 55 20",
				"3: 20 90 | 30 5",
				"7: 20 53 | 30 123",
				"86: 30 5 | 20 53",
				"105: 20 87",
				"46: 134 20 | 87 30",
				"102: 30 111 | 20 103",
				"93: 87 20 | 87 30",
				"79: 116 20 | 71 30",
				"8: 42",
				"33: 5 20 | 87 30",
				"107: 96 20 | 123 30",
				"90: 20 30",
				"110: 20 59 | 30 32",
				"16: 30 68 | 20 39",
				"52: 4 20 | 38 30",
				"71: 96 30 | 51 20",
				"38: 96 20 | 90 30",
				"28: 20 30 | 30 30",
				"27: 30 64 | 20 24",
				"91: 30 27 | 20 113",
				"1: 20 90 | 30 134",
				"54: 105 20 | 18 30",
				"0: 8 11",
				"73: 65 20 | 55 30",
				"132: 30 17 | 20 19",
				"41: 20 51 | 30 22",
				"45: 22 30 | 53 20",
				"14: 124 20 | 73 30",
				"22: 30 30",
				"23: 87 30 | 55 20",
				"10: 30 89 | 20 134",
				"120: 56 30 | 9 20",
				"11: 42 31",
				"109: 95 134",
				"127: 30 53 | 20 123",
				"61: 20 53 | 30 90",
				"103: 127 30 | 23 20",
				"116: 90 20 | 87 30",
				"134: 20 20 | 30 20",
				"114: 20 63 | 30 41",
				"64: 20 118 | 30 25",
				"12: 30 48 | 20 3",
				"111: 20 23 | 30 72",
				"60: 79 30 | 120 20",
				"59: 20 28 | 30 87",
				"65: 20 30 | 20 20",
				"44: 89 30 | 28 20",
				"18: 65 20 | 43 30",
				"32: 95 123",
				"83: 30 66 | 20 22",
				"63: 20 123 | 30 55",
				"48: 30 134 | 20 43",
				"99: 20 12 | 30 125",
				"43: 20 20",
				"133: 20 100 | 30 110",
				"80: 20 50 | 30 44",
				"125: 20 98 | 30 86",
				"135: 128 30 | 130 20",
				"131: 20 55 | 30 134",
				"122: 97 30 | 60 20",
				"25: 30 43 | 20 51",
				"95: 20 | 30",
				"55: 30 95 | 20 30",
				"13: 43 20 | 43 30",
				"21: 20 76 | 30 80",
				"98: 89 30 | 65 20",
				"81: 106 30 | 85 20",
				"53: 30 30 | 20 20",
				"78: 45 30 | 37 20",
				"89: 20 30 | 30 20",
				"9: 96 30 | 43 20",
				"31: 2 20 | 82 30",
				"56: 5 20 | 96 30",
				"76: 1 20 | 23 30",
				"62: 92 30 | 10 20",
				"58: 30 22 | 20 43",
				"85: 77 20 | 67 30",
				"26: 30 58 | 20 6",
				"101: 30 81 | 20 91",
				"29: 83 30 | 47 20",
				"126: 20 53 | 30 55",
				"2: 122 20 | 135 30",
				"15: 5 30 | 51 20",
				"34: 20 37 | 30 116",
				"82: 30 104 | 20 132",
				"19: 40 20 | 62 30",
				"108: 21 20 | 119 30",
				"36: 30 22 | 20 87",
				"104: 69 30 | 99 20",
				"100: 20 7 | 30 61",
				"39: 89 20",
				"87: 30 20",
				"113: 52 30 | 34 20",
				"5: 30 30 | 30 20",
				"40: 4 30 | 107 20",
				"97: 20 26 | 30 78",
				"67: 30 131 | 20 126",
				"118: 20 134 | 30 66",
				"124: 96 30 | 22 20",
				"128: 30 114 | 20 14",
				"119: 30 49 | 20 74",
				"84: 129 30 | 33 20",
				"74: 30 6 | 20 46",
				"49: 30 38 | 20 75",
				"57: 117 30 | 108 20",
				"69: 20 94 | 30 115",
			},
			inputResults: []inputResults{
				{input: "aaabbaababbababbabaabbbaaabbbbaa", want: false},
				{input: "baabaabaaaabbabbbbbaaabb", want: true},
				{input: "aabbbaaabaaaabbbbaabbaaa", want: true},
				{input: "bababbbabbabbaaaaabababbbbaaaaaaaaabbaabaaaaabababaaabbaababbaab", want: false},
				{input: "baababbbbbbaaaababaaaababbabbaaaaabbbbbbbabaabaaaaabbbbb", want: false},
				{input: "abbaaabababbaaaabbaabababbbabbaa", want: false},
				{input: "aaabaaabaaabaaaaaaabbbab", want: true},
				{input: "abaaabaabbababababaaabba", want: false},
				{input: "aabbbbbbaaabbaaaabbabbbb", want: true},
				{input: "aabbbabaaaababaabbbababb", want: true},
				{input: "aaabbabbbaabbabbabaabbba", want: true},
				{input: "bbbaaaabbbabbbaaababbaabaaabaaaabbbbabba", want: false},
				{input: "babbbbaaaaabaaaabaaababbbabbaabbbaababbaabaaabab", want: false},
				{input: "aabaaaaabbaaaaaabbababbbbabaaaaabbaaaabb", want: false},
				{input: "bbbbababaaabbaaaaababbaa", want: true},
				{input: "baabaaabbbbbababababaabbaaabbabbaabbbaab", want: false},
				{input: "bbaabbabbbabbbaababbbbbabaabaabbbababababaaabaaa", want: false},
				{input: "baabbbbbaaaabbbabbbbbbbb", want: true},
				{input: "bbabbaabbbabbaaabbbaabaabaaabbbbaababaaa", want: false},
				{input: "babbbaababbbabbababaabbb", want: true},
				{input: "aabbbbbabbbbaaaabbbaabababababbb", want: false},
				{input: "aabbabaababababababbaaabaaabaabb", want: false},
				{input: "aabababbaaaaaaaababbbbaaabaaaaaa", want: false},
				{input: "abbbababaaabbaabababababbaaabbbbaaabaabb", want: false},
				{input: "baabbabaaabaaaaabbbbbaabababaaaa", want: false},
				{input: "abbbbabbbababbababbaabbbbaaaabba", want: false},
				{input: "abababbababaaabbabaabbbb", want: true},
				{input: "aaaabbbaaaaaabaabaaabbba", want: true},
				{input: "bbaabaababaaaabbaaaaaabb", want: true},
				{input: "aaabbabbaabaabbbaabbaaba", want: true},
				{input: "aaaaabaabbaabaababbabaaa", want: true},
				{input: "bbabbbbabbbaabbbabbbbaab", want: false},
				{input: "aaabbabbbaaabbbbbaabaabbbabababbaaaaaababbbbaabb", want: false},
				{input: "abaabbabbabaaabababaababaabbabbbabbbbaaaaabbbbaabbaaaaababbbabbaabbbbbabaabaabbabbbbbaabaaaabbab", want: false},
				{input: "bbbaababaaaabababaaaaaab", want: true},
				{input: "bbbbabbbaaababbbaabbbbbb", want: false},
				{input: "babbbaabaababbbaabbbbbaa", want: true},
				{input: "abababbabbbabbabbbbabaaa", want: true},
				{input: "abaabaaaaabaabbabaaabbbbbbababab", want: false},
				{input: "abababbaaabababbbababaaa", want: true},
				{input: "baaabbabbbbbbabababbaaababbbbabbbaababbbaabbbbabbbaaabbabbbbbbab", want: false},
				{input: "aababbbaabababaaaaaaabab", want: true},
				{input: "baaabbababbaaaababbabbbabaaabaaabaabbbbaaabbabaabbbaabbbabbabbabaabbaaab", want: false},
				{input: "baaaabaabbababbbbbbbbababaaabaab", want: false},
				{input: "bbabbaababbabaabaaabaaabaaaabbaaabbbbaab", want: false},
				{input: "bbbaaaaaabbaaaaabaaaaaaa", want: true},
				{input: "bbabbbaababbbaaaababababbbaabaabbbbbababbaaabbbaabbaaaabbaaaaaaa", want: false},
				{input: "abbbbabbaabbabbbaaaaabba", want: true},
				{input: "babbababbaaabbabbabbaabaaaaaaaba", want: false},
				{input: "bbbbababbababbbbabbababbaaababab", want: false},
				{input: "abbaaaababbabbbbbabbaaabaababaab", want: false},
				{input: "aabbbbbbabaabababbbabaaa", want: true},
				{input: "aaaaaaaababaaabaabaabbaaabbabbbaabaaaaaabbaabbba", want: false},
				{input: "abbbababaaaaabaaaababbbaaaabbaaa", want: false},
				{input: "bbbbbabbaabaaaaaaabaabbaaaaabbaa", want: false},
				{input: "ababbabababbbaabababbbaaabaabbbb", want: false},
				{input: "ababaabaabbabbbabbbabbbabbaaaababaabbaaa", want: false},
				{input: "ababaabaaaababbbbaaaabaabababbaaabbababb", want: false},
				{input: "aaabbbaabaabbbbbbaaababbaaaabbbabbbbbbbb", want: false},
				{input: "aaababbbaaaabaabbababaab", want: true},
				{input: "aabbbabaababbbabbaaaabab", want: true},
				{input: "abaabbbbbbabaabaaababababbbabaabbaabbaabaabababbabbaaaababaaaaaa", want: false},
				{input: "abbaaaababaaaabaabbbbbabbbaaabaaaabbabaa", want: false},
				{input: "babaaaaabbbaabababaaabbb", want: true},
				{input: "abbbbbbaabaabaaabbaaaaaabbabbbaabbabbbbbaabbbbababbababb", want: false},
				{input: "baabbababbbabbababbbbbaa", want: true},
				{input: "bbabaababbbabbabaabbbaab", want: true},
				{input: "ababbbabbbbbabaabaaaaabb", want: true},
				{input: "babbbbbbbaaaabbbabbbbaba", want: true},
				{input: "babbabaabaaabbababaababaababaaab", want: false},
				{input: "aaaababaaaababaaabbbabbaabbaaaabaaaabbab", want: false},
				{input: "abbaabbbbbabbabbababbbbbbbbabbaabaaaababbbbaabbabaaaabbbbabaaaabaaaabbab", want: false},
				{input: "baabbbbabaabbbbabaaabaaa", want: true},
				{input: "aaabbaaaaaabbabaabaaaaab", want: true},
				{input: "abbabaabbaaababbaabbabab", want: true},
				{input: "aabaabbbbaababbabbbbbaaabbbaaabb", want: false},
				{input: "aaaaaaaaaabbabbbaabaaabbabaaabababbbaababbaaabababbbbaaaaaabbbababaaaaaa", want: false},
				{input: "babbabababaaaababaaaabba", want: true},
				{input: "abbaaaaaaaabbaaabbbaabaaabaaaabbabaabaaabbbaabbbbbbaabbbbbaabababababaab", want: false},
				{input: "bbabaababaabbabbbbaaaaba", want: true},
				{input: "bbabbbaaaabaaabbbbbabbbaaabbbbba", want: false},
				{input: "babbbaaaaabbaaaababbbabb", want: true},
				{input: "bababbabbbaabaabbbbaaaaabaabbbab", want: false},
				{input: "bbbaaaaabababbaabaaaaaab", want: true},
				{input: "babababbbaabaaaaaaaabbbaabbbabbb", want: false},
				{input: "aaaaabaabbabbababbaabbba", want: true},
				{input: "aabababbabbabbaabbbaabbb", want: true},
				{input: "baaababbaabbaaaaaabbbabb", want: true},
				{input: "bbaababbaaabbbaababababbaabbaaabaaababab", want: false},
				{input: "baaaabaaababababaabbabbbabababbaaababbbbbbbaabba", want: false},
				{input: "babbbbabbbabbababaabaaabbbbaaaabababaaab", want: false},
				{input: "baaaaabaaabbbbaaabbaabbaabaabbbabababbabbaaabaaaaaabaaababaabbabbabaaaaaaaabbbbb", want: false},
				{input: "babbbaaaabbbbbbbaaaababbaabbbbbbbbbaaaabbbabbbbabaababaa", want: false},
				{input: "baabbbbbabababbaabababaabaabaabaaababbbbbbaabbaa", want: false},
				{input: "babaaababaaaaabaaabaabbabaaabbabbaaaabaabbbaabbbbbabaaabaaaaabbabbbabaab", want: false},
				{input: "abbabaaababaabaaabaaabaaababbbaababbababbaaabaaababbaaaa", want: false},
				{input: "ababaabaabbababaaaabbbbb", want: true},
				{input: "baababbabaabbbbbbbbaabaaababaaabbbbbbbaa", want: false},
				{input: "aabbaaabbbbababbababbaaa", want: false},
				{input: "babaabbabbbbbabbabbbbaba", want: true},
				{input: "abbbabbbbaaababbabaabbaabbbabaaa", want: false},
				{input: "babbbaaabaaaabaaaaabaaabbaaabbbbbabbaabaabaaabba", want: false},
				{input: "bbbbabbbbabbaababbabbbbb", want: true},
				{input: "bbbbaaaabaabbbabbbbabbaaaabbbaab", want: false},
				{input: "babbbbbababababaaaaabaaa", want: true},
				{input: "babbaabbbabaabbababaaaab", want: true},
				{input: "abbbabbabbababbbaabbbbaa", want: true},
				{input: "aaabbaababbbabbbbbaabaaa", want: true},
				{input: "babbaabaabaabaaaaaaaaaaabababbba", want: false},
				{input: "aabaaaababaaaabaababbbababbbababaabababa", want: false},
				{input: "bbbabbbbaaababbaabbbaaaabbbbbaabbabbbbbaaaabbbbaabbbaabb", want: false},
				{input: "abbabababbabbaaaabaabbba", want: true},
				{input: "abbaaaabbaaaabbabbbababaabbbabaa", want: false},
				{input: "abbaaabbbbaaababbbbaaaabbabbbbbabbbababbaababbab", want: false},
				{input: "baaababbababaababbbbabaaaabbababbaaabaaa", want: false},
				{input: "babbaaabbaabbbbbaabaaaaababbabaabaaabaabaabbbabbbabaabaa", want: false},
				{input: "aaababbbaaaababaababbaab", want: false},
				{input: "baaaabbbbaabbbaaabbaabbb", want: true},
				{input: "babbbaabaabbabababaaaaabaabbaabababaabbb", want: false},
				{input: "abbabbbbabababbababbaabaaaaaaaababbaaabbabbbbbaabbbabbabbbbababb", want: false},
				{input: "baaabbbbabbbaaaabbbaabba", want: true},
				{input: "abababaabaabaabbbbbabbbaaaabbababaabbbaabbababab", want: false},
				{input: "aaaabaababababbaaababbbabbabbaabaabbbbabbbbbbbaaabaaaaaa", want: false},
				{input: "aabaaabababbbaabbbbbbbaa", want: true},
				{input: "aabaaaabbaabaaaaaaaaabba", want: true},
				{input: "babababbaabbbaaaabbaaaba", want: true},
				{input: "abbabbbaaaababaaaabaaaaaaabbbbbbabaaabbb", want: false},
				{input: "bbbaaabaaabaababbbbaabba", want: false},
				{input: "bbabaababbbbbabbaaaababaaabaaaaaabbbbaaabbaabaaa", want: false},
				{input: "aaaababbbababbababbbbbbaaaabaaaaabbaaabaabbbbbaabababaab", want: false},
				{input: "baabbbbbaabaaaababbabbaaaaaabaaa", want: false},
				{input: "bbbbbaabbbbbabaababbbaaabababbbbbbbaaaaaabbbbaba", want: false},
				{input: "ababbaabaabbaabbaaaabbbb", want: true},
				{input: "bbbbbaabaabbbbbbbaaaaaaa", want: true},
				{input: "bbbbbaaabbbbabbbaabaaabbbabaabbb", want: false},
				{input: "bbbbbaabaaababbaaaabbaaabbbbababbabaabbabbbaaabbaaaaabbb", want: false},
				{input: "baabbbaabaabbababbababbabaaaabab", want: false},
				{input: "abaababbabbabbaaababbbba", want: true},
				{input: "aaabbaababbabababababaaabbabbbbb", want: false},
				{input: "aaababbbbabbabaaabaabaaabbbbaaba", want: false},
				{input: "baaababbbabbaaabbaabaaaabbbababb", want: false},
				{input: "abbbbbbaabbbabbaaabaaaabbbababbbaaabbbab", want: false},
				{input: "bbbbbababbbaababbababaab", want: true},
				{input: "aaaababababbbaaaabababbb", want: true},
				{input: "bbabbaababbababaaabaaababbbbababbbbbbbabbbaaabbb", want: false},
				{input: "abbbbbbbaabaabbaaabbbaab", want: true},
				{input: "bbbaababbbbbbaaaaaaabbab", want: true},
				{input: "babbbbbaaaaababbaaaaaabb", want: true},
				{input: "baabbbaabaabbababbabbabb", want: true},
				{input: "baabbababbbaababaabbabba", want: true},
				{input: "baababbabaaabbabbaaababbbabbbbbbbaababbbbabbbabbbababaab", want: false},
				{input: "bbaaabaaaaababbaaaabbbab", want: true},
				{input: "babaabbaabbbbbbbbabaabbb", want: true},
				{input: "ababaabaaaabbbaaabababaaaabaaabbbaaaaabb", want: false},
				{input: "baabbabbaabbaabbaaaabababbabaaab", want: false},
				{input: "aabaabbbaaababbbabbbbaab", want: true},
				{input: "bbbbbaaaaaabbabababbbbaaaabbbabb", want: false},
				{input: "baaabaabbaaabbbabaabaaababaabababbbababababbaaababaabaabbbbabbabaaabbabbaabbaaabaaabaaab", want: false},
				{input: "aabbbbbbaabaaabbbbabbaaabaaaaabaabbbaaaababaabaa", want: false},
				{input: "aaaabaabbababbabbbbabbbbaabbbababbbaaabaababaaaaabbabbab", want: false},
				{input: "babaababaaaabaabbaabaabbbaabbababbabbbbb", want: false},
				{input: "bbbaababbbbaabaaabbbabbbabbaaaba", want: false},
				{input: "baaaabbabbbbaaaaaaaaabbbbbabababbbbababaaababbbabbababababbbbbba", want: false},
				{input: "abbbabaaabaabbbaaabaabaabbbbbbab", want: false},
				{input: "babaaaaabaabaabaaaabaabb", want: true},
				{input: "aabababbabaabaaaaaaabbbabbaabbabaaaabbabbaaabbba", want: false},
				{input: "ababbbabbbbbbaaaaaabbaababbbaaaaaaaaabba", want: false},
				{input: "baabbabbbbabbaababbabbaaabaabbba", want: false},
				{input: "bbaaababbabbabbabbabbaabaaaaaababaabaaabaababaaa", want: false},
				{input: "baabbbbbbbbaabaaabbabaaa", want: true},
				{input: "abbabababaaabbabbaaaabab", want: true},
				{input: "ababbababaabaaabaabbbbbbbbbabaab", want: false},
				{input: "baabababbaaaabbababbaaaaabaabbaa", want: false},
				{input: "abbaaabbabbabbabaaaaabbbbabbbbaaababbbbbaababbabbaababbaabbbabba", want: false},
				{input: "abbbbababbabaabaabbaaaabbaabbabaaabbaababaaabaababaaaabbabababba", want: false},
				{input: "babbaaabbbabbabaaaabbbab", want: true},
				{input: "aabbbaaaabbbbabbaaabbbbb", want: true},
				{input: "baababbbbaaabbababbbabbbbbaaabaaaabbaaaaaaaabbab", want: false},
				{input: "babaabababababbababbbbbaabbabaaa", want: false},
				{input: "babaaabaaaabbabbaabaaababbaabaabbaababbbabaabbbabbbbabbaabbaabaa", want: false},
				{input: "baababbabababbabbbabbaabbaabbbaabbbababb", want: false},
				{input: "baabaabbababaabbaabbaaaaaaaaabba", want: false},
				{input: "aaaababbbabbaababbbbaaba", want: true},
				{input: "bbbabbbaaaaababbaabbbbaa", want: true},
				{input: "abaaaabaaaaaaaaaaaabbaaaabaabbab", want: false},
				{input: "ababbaabbabbaaaabbbbaaab", want: false},
				{input: "baaabbbbabbbaabababaabababaabbbb", want: false},
				{input: "baabaabaaabaaabbbbbaabaaaabaababaabbbbba", want: false},
				{input: "bbbbabaababbbaabaaaaaabbbaaababa", want: false},
				{input: "abbabababaabbabbababbabb", want: true},
				{input: "babababababaaaaaabbbbbaa", want: true},
				{input: "aabbbbbbbabaaaaabbbaaaaaabababbbabbbaabbababbaaa", want: false},
				{input: "babababaabaababaababaaab", want: true},
				{input: "baababbabaabbbbaaaabbbaabaaabbabababaababaaabaabababbbbbbbabababbaaabbaa", want: false},
				{input: "abbbaabaaabbbabaaaabbbbb", want: true},
				{input: "bbabbabaabbabbbaaabbabbbaababbababbabaaa", want: false},
				{input: "abbaababaaababbbabbbbbab", want: true},
				{input: "aaababbababaaabbabbababb", want: true},
				{input: "baaaaabababaaabbbaabbbaabaaabaaa", want: false},
				{input: "aabaaaabbbbbababaaababbb", want: false},
				{input: "abaaaabbbabbabbaabbbbbbbabbaabbb", want: false},
				{input: "bababaaababbbbaaaaaabababaaaababbaabbbabbaaabbabaabaaaaababaaaabaabaabbabbbaaabbaababaab", want: false},
				{input: "aabbabbbabbaaaaaaaababab", want: true},
				{input: "bbbaaaaaababbaabababbbba", want: true},
				{input: "ababababbbababbbaaabbaabbababbbabbaabbaa", want: false},
				{input: "aabbabaabaaabaabaaabaabaaaabaabbbbababbaaaababababbbbbabbbaabaaababbaabababaaaabbaaaaaba", want: false},
				{input: "abbbbabbbbaaaaaabbaabaaa", want: true},
				{input: "aaaababbbabaaabbbabaababaaabaaabaaaaabbb", want: false},
				{input: "ababbbaaabbabbaabbaaabbb", want: true},
				{input: "abaaaabbbaabbbaaaaabaaabbbabbbba", want: false},
				{input: "aaabaaaaaaabbabaabbabbaababbbbbaabaabbbb", want: false},
				{input: "aaabbabbbabbbaababaababbaaaaabbbaababbbb", want: false},
				{input: "aabaabaabaaaabbabaaabbaaabbabaaaaabbabbbbbabaaaabbbababbaabaabbb", want: false},
				{input: "abaabbaababbaaabbabaaabbbabaabbabbabbabaabbbbbabaababbaa", want: false},
				{input: "ababbbabbbbabbbbbaaaabbbabbabbbaaaaaaaab", want: false},
				{input: "abbbabbabaaabbababbbababaaabbaabaaaaabba", want: false},
				{input: "abaaaabababaaaaabbaabaabaababaaa", want: false},
				{input: "bbbbbbabbabbbbaaaaabbbabbbaaaabaaabaabab", want: false},
				{input: "bbbaaaaaabbbbbbbaabababa", want: true},
				{input: "baabaaaabbbabbbaabababbb", want: true},
				{input: "aabbbabaaaaaabaabbbabbaa", want: true},
				{input: "babaaabbaaaaabaaabbbbbbbbabaaabbaaaaabab", want: false},
				{input: "bababbbbbaabbabbbbaaabbb", want: true},
				{input: "bbaabbbaabbabbbbaabbbabb", want: false},
				{input: "abbabaabbabbaabaaababaaa", want: true},
				{input: "bababbaabaabaabbabbabbab", want: true},
				{input: "bbbaababbabbabaabaabbbbabaaaaabbbbbbaaab", want: false},
				{input: "bbbaababbabbbbaabababbba", want: true},
				{input: "babbaabbbabbabaaaabbabbbbabaaaabbbbababb", want: false},
				{input: "bbaabaababaabaaaababaaababaaabbaababbbbb", want: false},
				{input: "abbbabbbaababaaaaaabbabbabababaaaaababaaaaababbabbaababb", want: false},
				{input: "abbaaabbbaabbabbabaabbaaaababbbabbaabaabababbbabaaabbbab", want: false},
				{input: "abbbaaaaaabbbaaabbaaabbb", want: true},
				{input: "bbbbbabbabbabbaaabbabbbb", want: true},
				{input: "baabbabaaaaabababaaaaaab", want: true},
				{input: "aaaababbbbbabbbaaaababaabababbbb", want: false},
				{input: "abbbabaabbbababbbbabbbaaaaaaabaaaaaaabbbaaababab", want: false},
				{input: "baaabbbbaaabbaabbaaabbababbaababbbbaaaba", want: false},
				{input: "bbaababbbbbbbababaaababbabbabbbaaabbbabaabbbabbbbaaabaabaaabaaba", want: false},
				{input: "aaabaaaabbbbabbbbabbbabb", want: true},
				{input: "bbabbaababaababababbabbb", want: true},
				{input: "babbaaababbbbabbabbbaaabaabbabba", want: false},
				{input: "bbabbaabbabbabaababaaaaaaababbabbaaabbaababbbbbaababbbabaababbabbbabbbaabbbabbbbabaabbab", want: false},
				{input: "baabaaaaabaaaabbabbbbbbbaabbbaaabaaabbabbabbabbaaaaaaababaaababaaaaaabbb", want: false},
				{input: "bbaabbabbbaaabaabbaababa", want: true},
				{input: "aababbbabbbaabaaaaabbbab", want: true},
				{input: "baabbbbaabbabbaabbaaaabb", want: true},
				{input: "bbabbaabbaaaabaaaaaabbbb", want: true},
				{input: "baabaabaaabaabbaabababbb", want: true},
				{input: "abaabbaabbaabaabbbaabbabaaabbbaaaaaaabbb", want: false},
				{input: "bbbbbababbaaababbaabbaaa", want: true},
				{input: "bbaabbabbbabbaaabaabbbab", want: true},
				{input: "bbbaaaaaabbbbbbbaabbabaa", want: false},
				{input: "bbaaababbbabaabbaabbaaaaaaabbbbbbaaababaabbbbbbbbabaabaaaabbabab", want: false},
				{input: "aabbaabbbabbaaabaabbaaaabbababab", want: false},
				{input: "abbbabbaaaababbaabbaaaaa", want: false},
				{input: "aaabbabbbbaabaabbbabbaaaabbaaabbbabbbaba", want: false},
				{input: "abaabaaababbababaaababbbaabbbabb", want: false},
				{input: "abaaaabababbbbbbaaabaaaaabababbaaabbbbab", want: false},
				{input: "abbaabbbbbabbbbabbbaaababbabaaabbbabbbab", want: false},
				{input: "babbbbbbbabaabbabaababbaabaabaaaabbbabaababbbbab", want: false},
				{input: "bbbabbbbaabbaaaaabbaabaa", want: true},
				{input: "bbbbbaaababababbbaaababa", want: true},
				{input: "baabbbaabaabbababbbaababbbababbbabaabbbb", want: false},
				{input: "bbaababbbabaaabbabbbaaab", want: true},
				{input: "baabaaaaabbaaaaabbbaaaabbabbabbaaabbbaaaaabaabbbbbbbaaba", want: false},
				{input: "abbbababaaaaabaaababbabb", want: true},
				{input: "aaaaabaababbaaabaaaababbbaaabbbbababaaaa", want: false},
				{input: "ababbaababbabbbababbabbabbabbaababaaaaabbbbbaaaabbbaaaba", want: false},
				{input: "baaabaaabbbbabaaaababbaabbbaaabaababbabbaaabaaba", want: false},
				{input: "bababbaaababababaabbabbbaabaabaaabaaabbaabbbaaaaabbbabaa", want: false},
				{input: "abbaaabbabbaababbbaaaaaabbaaaabb", want: false},
				{input: "bbaabaabbbbaaaaabababababbabbbaaaaabbbba", want: false},
				{input: "bbaababbabbababaabbbaababbabbabbbbabaaab", want: false},
				{input: "abababaaabbbaaaabababbaaabbbaaababaaaaab", want: false},
				{input: "abbabaababbbbabbbbaabbbb", want: true},
				{input: "ababbaabbabbabababaaabbb", want: true},
				{input: "aababbbabababaababbbbbbaababbabbaababbbbbbbbaaaababbaabbbaaaaabb", want: false},
				{input: "abbbaaaaaabababbababbbba", want: true},
				{input: "babbabaaaaabbbaabaaabbaa", want: true},
				{input: "aabaaababaabbbaaaabaaababaaababbabbbaaaaaaaabbaa", want: false},
				{input: "bbaabbabbbabbabaaabbaaba", want: true},
				{input: "bababbaabbbaababbaaaabaaabbbbaab", want: false},
				{input: "bbbabbbabbbabbababbbaaab", want: true},
				{input: "abbbbbbbaabbabbbaaaabaabaabbaaabaaaabbbb", want: false},
				{input: "bbbbbabbbaababbbaabbaaba", want: true},
				{input: "ababababababababababbabb", want: true},
				{input: "baaaaaaabbabbaababaaabbb", want: false},
				{input: "bababbaaabbabababababbabaabaabbabbaababaababbbbb", want: false},
				{input: "bbabbaaabbbbaabaababababaabbbbabbabaabbbbaabbbaabbaaaababaabaabb", want: false},
				{input: "abbababaabaaaabbbabaaaab", want: true},
				{input: "bbabaabababbaabbbabbbbbbabbbbaabaabaabaa", want: false},
				{input: "bababbaaaabaaaaabbbbaabb", want: true},
				{input: "bbaabbabaabaabbbbabaabbaababaaababbaaaab", want: false},
				{input: "babaaabaaabaaaabababaabababbbaba", want: false},
				{input: "babbbbbaabababbaaaabbaabbabbabaabbaabbbb", want: false},
				{input: "abbababaabababaababaaababbbabbaa", want: false},
				{input: "aabaaaaaabbabbaabbabaababaababbaabaaabbb", want: false},
				{input: "abaabbaabbbbbaaaabbaabba", want: true},
				{input: "babaabbabaabbbbbbbabbbaababbbaabbbbababbaabbbaaabababbbbbaaababaabbbabbabbaaaabbaababaabaaaabbba", want: false},
				{input: "aaaabbbabbaaababaaabbaaaabababaababbbbababbaabbb", want: false},
				{input: "baabbabaabbaababaabbabab", want: true},
				{input: "ababaabbaabaaabaabbababb", want: true},
				{input: "aabbbababbaabbabaaaaabaa", want: false},
				{input: "ababaababbbabbbbbaaaabab", want: true},
				{input: "ababaababaaaaababbbabbbaabbbabaa", want: false},
				{input: "abaabbaaabbabababbbbabba", want: true},
				{input: "babbbbbabbaaaaaaaaaaabab", want: true},
				{input: "bbabbababbbabbbbababbbbb", want: true},
				{input: "abaababbabbaaabbbbbbababbbbbaaaa", want: false},
				{input: "abaaaabbbababbbbaababbbb", want: true},
				{input: "baabaababababbbbababbabb", want: true},
				{input: "baaaabaaaaabbabbabbabababaabbababbbbabaaabaaababbabbaaaa", want: false},
				{input: "aaaaaaaabbbabaaabbabbabaaabbbbaaabaaababababbabbabababab", want: false},
				{input: "bbbaaaabaaabaaaaaabaabbbbababaab", want: false},
				{input: "baabbbbabaaaaabaabbbaabb", want: true},
				{input: "abaaaabaabbaaaaaabaababbbaaabbba", want: false},
				{input: "ababbbaabbbaabaaaaababab", want: true},
				{input: "aaababbabbbbbabbabbbaaaabababaab", want: false},
				{input: "bbbbabbbbababbabaabbbbba", want: true},
				{input: "baaabbbbbbbbbaaabbaaabaaabaaabbaaababbab", want: false},
				{input: "bbabbaabababbbbbbbbaaabbabbbaaba", want: false},
				{input: "aaabbababaabaaabbaababbbbbaabbababbaaabbbbabbabbaabbbbab", want: false},
				{input: "abbaaaaabbabbaaaabbababb", want: true},
				{input: "baabaabbbaabbabababbaaabbaaaaababaaaabbabbbbbbaa", want: false},
				{input: "babbaabaaabababbbabbabaaabaaaaabbbaaabbb", want: false},
				{input: "babababbaabbaabbbbbbaaab", want: true},
				{input: "babaaababbbaabaaaaaabaabbbbaaaabababbaaa", want: false},
				{input: "aaabbbbbbbabababaabbabba", want: false},
				{input: "baaabbaaaaabbbbaaababbaaabbaaaaabbabbbbbabbbabbbbbbaaaaabbaaaababaaabbbbbaabbaababbbbbbababbaaaa", want: false},
				{input: "ababbababaabbabaababbbababaababbabbbaaaabbbbbbaaabbababb", want: false},
				{input: "babababababababaaaaabbab", want: true},
				{input: "aaabbaaaabbbbabbabaaabbb", want: true},
				{input: "babbbaaabababbaabaabaabaabbaababaaaabaaaababaaab", want: false},
				{input: "babaaaaaabbbbabbbbaabbba", want: true},
				{input: "bbabbaabaabbbaaaaabaaabaabbbababaabbaabaababaaaaababbbba", want: false},
				{input: "aabbbabaabbabbbababbaaaa", want: true},
				{input: "baaaabaababbabaabbbaabbb", want: true},
				{input: "aaabbabaaaabaaabaabbaaaabbaabbaa", want: false},
				{input: "abaabaaaabbabbaabbaababbabababbabbbbaabbbbaabbba", want: false},
				{input: "bbbaaaaabbabbabaabaaabaa", want: true},
				{input: "ababbbabbabbaababbaabbaa", want: true},
				{input: "aaabbaaaababbbabbaabbaaa", want: true},
				{input: "aaaaabaaabbabbaaabbbbaab", want: true},
				{input: "bbbaaaababaabaaabbbabbbabaabaaaabaabbbaaabbabaabaaaabbbb", want: false},
				{input: "babaaabababbbbbaaaaabbaa", want: true},
				{input: "baabaabbbabaabaabbaaaaab", want: false},
				{input: "baababbbbaaabbabaababbbb", want: true},
				{input: "bbaababbbbababbabbabbbbb", want: true},
				{input: "abbaababaabaabbaabbbbbbbbbaabbbbbbaababa", want: false},
				{input: "babaaaaaaaababbaabaaabab", want: true},
				{input: "babaaaaabbaabbaabaabbaabbbaabaaabbbbaabbbbbaabba", want: false},
				{input: "bbbaaabaaabbbabbabbaabbb", want: false},
				{input: "bbbbabababbaaaaaaabbbaaabbbbabaabbaaaaaabbbbaaaa", want: false},
				{input: "bbbaaaaaabaabaaabaaababa", want: true},
				{input: "aaabbababaaabbabbabaaaaaaaababababbbbaab", want: false},
				{input: "babbbbbabababbababaaabbb", want: true},
				{input: "aabababbaabbabbbbbbbbbba", want: true},
				{input: "abbabbaaabaababbbabbabbaaaaabaabaabbbbba", want: false},
				{input: "babbabbaabababbabababbbbaaababaaabbaaabbaabaabaa", want: false},
				{input: "aaaaaaaabbbabbbaabaaabba", want: true},
				{input: "baaaabaaabbbbbbaaabaabbbbbbbaaaa", want: false},
				{input: "abbbaaaabababaaabbbbbabbabaaabaaaaababbbabaababaabaaaaaa", want: false},
				{input: "abaababbabbbbbbaaabbabbbabbaaaab", want: false},
				{input: "abbabbbababbaaabbbabaaaabaababaaabbaabba", want: false},
				{input: "aaaabaabbbababbbbabbbbaabbbabbababaaaaab", want: false},
				{input: "abbaaabbabaababbbaabaababaaababa", want: false},
				{input: "abababababbaaabbbaaabbababaabaab", want: false},
				{input: "baaabbabaabaabbaaabababa", want: true},
				{input: "bbaaabaaaaaaabaababbaabb", want: false},
				{input: "ababbabaaabbabaaaabababa", want: true},
				{input: "babbbbaabbbbbaabbbaababa", want: true},
				{input: "babaaaababaabbababbabbbaabaaabababbabbaaaabbaabb", want: false},
				{input: "baaababbaaabaaabaabbabbbbaaaaaab", want: false},
				{input: "abaabbaabbabbaabaabababbabbabbbb", want: false},
				{input: "bbbaababaababbbabbababab", want: true},
				{input: "baababbabaaaabaaabababbababaaaab", want: false},
				{input: "babbaababbabaaaaababbaaa", want: true},
				{input: "aababbbaaabababbaabaabab", want: true},
				{input: "bbaabbabaabbbbbbbbababbbaaaabbbabbbbaaba", want: false},
				{input: "bbaaababbbaaabaabbbaaabaababbbbababbbabbababbbbaabaabbba", want: false},
				{input: "bbabaaaaaabbbababbaaabbb", want: true},
				{input: "baaaabaabaabbababaabaaababbbaabbbbabbaabbbbabbabaaababaaaabbaaaaaaaabbabaabbbabaabbabbaa", want: false},
				{input: "abaaaabbaabbabaaaabbbababbabaaaaaabbaaba", want: false},
				{input: "baaaaaabbbabbbbaabbbbbbbbbabaabbbabbabababaabababbbbaaabaaaabbbababbbbaa", want: false},
				{input: "aaaaaaaaaabbbabaaabbaaab", want: true},
				{input: "aababbbababaabbaaaabbbababbbaabb", want: false},
				{input: "abbbbabbaaabbbaaababaabbbabababa", want: false},
				{input: "aaaaabaabaaaabaaabbaabaa", want: true},
				{input: "bababbabbabaababbabbbabb", want: true},
				{input: "abbbbabbbaabbbabbbbaabaabbbaabbaaaaababaaaaaaaaababaaaba", want: false},
				{input: "aabaaababbbaabaabaabaaaabbbbaaababbbbaba", want: false},
				{input: "abbabaabbbaaababaaabaaba", want: true},
				{input: "bbaaababbbbbbaababbbabaa", want: true},
				{input: "bbabaaaababbbaaaabaaaaaa", want: true},
				{input: "aaabbaaabbabaababaaaabba", want: true},
				{input: "baabbabaaabbaaaaabbbbaba", want: true},
				{input: "baabaabababbaabbbbababaa", want: true},
				{input: "aaaabaabbbaaababaabbaabbabbbaaaaabaabaab", want: false},
				{input: "aaababbbaabaaaabbaaaabbbbabbbbba", want: false},
				{input: "aaabbbaababbaababbaaaaba", want: true},
				{input: "bbbabbbababbbaabbbaababa", want: true},
				{input: "abbbaaaabbabbbaaabbaabaa", want: true},
				{input: "aaaaaabbbbabbaaaabbabbbabaabbbabbbaaabaabaaaabaa", want: false},
				{input: "abababaaaaaaaaaaabbbaababaaaabbabbaabbabbabaabaaaabaabaababaabbabaabbbbb", want: false},
				{input: "ababbbaaabaabbaaabaababaabbbbbaa", want: false},
				{input: "abbabbbaababbababbbbbabaaabaabbabaabbabbbbaaaabaabaaabaa", want: false},
				{input: "ababbaabababbbabbbbbaaab", want: true},
				{input: "babbabaababaaabbbaabaabb", want: false},
				{input: "bbababbbaaabbaabbabbabaaaabaabaa", want: false},
				{input: "abaababbbaabbababaaababbbabaababbaaaaabaabbabbbb", want: false},
				{input: "ababababaaababaabbaaaabb", want: true},
				{input: "bbbaaaaaababbaababaabbba", want: true},
				{input: "babbbaababbbabbabbabaababaababbabbaababa", want: false},
				{input: "baabaabbbbaaaaaabbbaaabb", want: true},
				{input: "abbbaababbbbbabababbaabaaaaaabaaabbaaaaaabbbbaabaabbbbaaaabbbbabaababaab", want: false},
				{input: "ababaabbaabababbbbabbaabaaababaabaaaaababaaaabba", want: false},
				{input: "ababbbbbaabbaababababaababaaaaaaabbaaaaabbabbbaa", want: false},
				{input: "abbaaabbabaaaabbbbbabbbbbabbaabbbbbaaaaaabbbabbbbbbaabba", want: false},
				{input: "aaababbaaaaabaabbbaaababaaaabbbb", want: false},
				{input: "aabaaababbbbbbabaaabbabaabbaaaaabbbbbbbbababababbbaababbbabbabab", want: false},
				{input: "bbbaababbaaabbaabbbbbbaaabaaaaabaabbaababbaaaaab", want: false},
				{input: "aaaabbbaababbaabbabaabbababaaabbbaabbaab", want: false},
				{input: "bbbabababbababababbaabaa", want: false},
				{input: "bbbbabaabbaababbaaaabbbaabbbbbab", want: false},
				{input: "aaabbaaaaaaabbbaabbbbbbaabaaaabababbbaaabbaababbbaaaaaaaababbbbabababaaa", want: false},
				{input: "aaaaabbababbababbbababbbbaaababbabaabbaaaababbaabbaabbaa", want: false},
				{input: "bbabbabaaaaaabaabababbbbaaabbbba", want: false},
				{input: "ababbbaabbababbaaaaaaaab", want: true},
				{input: "babaaabbbaabbabaaaabaabb", want: true},
				{input: "babbababbbbbabaabababaab", want: true},
				{input: "bababbabbbaabaabbbbabaab", want: true},
				{input: "abbbaabaaabbbbbbaabbbbbbaabaaabbbbbbbaaaababbaaaaababaaabaaabaaa", want: false},
				{input: "abaabaaaabaababababaaabaaaabbbaabbabaaab", want: false},
				{input: "ababbbabaaaaaaaababbbbab", want: true},
				{input: "bbabbbbaabbbbabaaaaaabbbbababbaaabbbbbbbbbaabbbabbaaababababbbbbabbaabbabbabaaaabbbabbba", want: false},
				{input: "abaaaabbaaabbaabaaabaaaabbbabbbbababbbaabaabbbab", want: false},
				{input: "aabbbbbbbabbaababaabbababaabbbba", want: false},
				{input: "baaaabbbbababbabbbaabbba", want: true},
				{input: "abbbaaaaababbbababbabaaa", want: true},
				{input: "bbbabbbaaaababbaabaabbaaabaababaabbabababbaaabbaaaaaaabbabaabbabbbbaabbb", want: false},
			},
		},
		{
			startSymbol: "0",
			rules: []string{
				"77: 30 112 | 20 13",
				"121: 43 20 | 123 30",
				"42: 57 30 | 101 20",
				"30: a",
				"50: 65 20 | 134 30",
				"37: 89 20 | 43 30",
				"106: 16 30 | 54 20",
				"17: 30 84 | 20 35",
				"129: 89 20 | 96 30",
				"123: 30 30 | 20 95",
				"20: b",
				"115: 20 70 | 30 93",
				"112: 30 90 | 20 123",
				"4: 20 55 | 30 5",
				"72: 20 90 | 30 123",
				"51: 30 20 | 20 95",
				"24: 131 30 | 7 20",
				"94: 121 20 | 15 30",
				"117: 133 30 | 102 20",
				"92: 28 20 | 43 30",
				"70: 87 30 | 96 20",
				"88: 109 20 | 36 30",
				"35: 20 36 | 30 61",
				"96: 30 95 | 20 20",
				"47: 96 20 | 66 30",
				"6: 20 55 | 30 123",
				"130: 30 29 | 20 88",
				"68: 5 20 | 89 30",
				"66: 95 95",
				"75: 96 30 | 55 20",
				"3: 20 90 | 30 5",
				"7: 20 53 | 30 123",
				"86: 30 5 | 20 53",
				"105: 20 87",
				"46: 134 20 | 87 30",
				"102: 30 111 | 20 103",
				"93: 87 20 | 87 30",
				"79: 116 20 | 71 30",
				"8: 42 | 42 8",
				"33: 5 20 | 87 30",
				"107: 96 20 | 123 30",
				"90: 20 30",
				"110: 20 59 | 30 32",
				"16: 30 68 | 20 39",
				"52: 4 20 | 38 30",
				"71: 96 30 | 51 20",
				"38: 96 20 | 90 30",
				"28: 20 30 | 30 30",
				"27: 30 64 | 20 24",
				"91: 30 27 | 20 113",
				"1: 20 90 | 30 134",
				"54: 105 20 | 18 30",
				"0: 8 11",
				"73: 65 20 | 55 30",
				"132: 30 17 | 20 19",
				"41: 20 51 | 30 22",
				"45: 22 30 | 53 20",
				"14: 124 20 | 73 30",
				"22: 30 30",
				"23: 87 30 | 55 20",
				"10: 30 89 | 20 134",
				"120: 56 30 | 9 20",
				"11: 42 31 | 42 11 31",
				"109: 95 134",
				"127: 30 53 | 20 123",
				"61: 20 53 | 30 90",
				"103: 127 30 | 23 20",
				"116: 90 20 | 87 30",
				"134: 20 20 | 30 20",
				"114: 20 63 | 30 41",
				"64: 20 118 | 30 25",
				"12: 30 48 | 20 3",
				"111: 20 23 | 30 72",
				"60: 79 30 | 120 20",
				"59: 20 28 | 30 87",
				"65: 20 30 | 20 20",
				"44: 89 30 | 28 20",
				"18: 65 20 | 43 30",
				"32: 95 123",
				"83: 30 66 | 20 22",
				"63: 20 123 | 30 55",
				"48: 30 134 | 20 43",
				"99: 20 12 | 30 125",
				"43: 20 20",
				"133: 20 100 | 30 110",
				"80: 20 50 | 30 44",
				"125: 20 98 | 30 86",
				"135: 128 30 | 130 20",
				"131: 20 55 | 30 134",
				"122: 97 30 | 60 20",
				"25: 30 43 | 20 51",
				"95: 20 | 30",
				"55: 30 95 | 20 30",
				"13: 43 20 | 43 30",
				"21: 20 76 | 30 80",
				"98: 89 30 | 65 20",
				"81: 106 30 | 85 20",
				"53: 30 30 | 20 20",
				"78: 45 30 | 37 20",
				"89: 20 30 | 30 20",
				"9: 96 30 | 43 20",
				"31: 2 20 | 82 30",
				"56: 5 20 | 96 30",
				"76: 1 20 | 23 30",
				"62: 92 30 | 10 20",
				"58: 30 22 | 20 43",
				"85: 77 20 | 67 30",
				"26: 30 58 | 20 6",
				"101: 30 81 | 20 91",
				"29: 83 30 | 47 20",
				"126: 20 53 | 30 55",
				"2: 122 20 | 135 30",
				"15: 5 30 | 51 20",
				"34: 20 37 | 30 116",
				"82: 30 104 | 20 132",
				"19: 40 20 | 62 30",
				"108: 21 20 | 119 30",
				"36: 30 22 | 20 87",
				"104: 69 30 | 99 20",
				"100: 20 7 | 30 61",
				"39: 89 20",
				"87: 30 20",
				"113: 52 30 | 34 20",
				"5: 30 30 | 30 20",
				"40: 4 30 | 107 20",
				"97: 20 26 | 30 78",
				"67: 30 131 | 20 126",
				"118: 20 134 | 30 66",
				"124: 96 30 | 22 20",
				"128: 30 114 | 20 14",
				"119: 30 49 | 20 74",
				"84: 129 30 | 33 20",
				"74: 30 6 | 20 46",
				"49: 30 38 | 20 75",
				"57: 117 30 | 108 20",
				"69: 20 94 | 30 115",
			},
			inputResults: []inputResults{
				{input: "aaabbaababbababbabaabbbaaabbbbaa", want: false},
				{input: "baabaabaaaabbabbbbbaaabb", want: true},
				{input: "aabbbaaabaaaabbbbaabbaaa", want: true},
				{input: "bababbbabbaRbbaaaaabababbbbaaaaaaaaabbaabaaaaabababaaabbaababbaab", want: false},
				{input: "baababbbbbbaaaababaaaababbabbaaaaabbbbbbbabaabaaaaabbbbb", want: true},
				{input: "abbaaabababbaaaabbaabababbbabbaa", want: false},
				{input: "aaabaaabaaabaaaaaaabbbab", want: true},
				{input: "abaaabaabbababababaaabba", want: false},
				{input: "aabbbbbbaaabbaaaabbabbbb", want: true},
				{input: "aabbbabaaaababaabbbababb", want: true},
				{input: "aaabbabbbaabbabbabaabbba", want: true},
				{input: "bbbaaaabbbabbbaaababbaabaaabaaaabbbbabba", want: true},
				{input: "babbbbaaaaabaaaabaaababbbabbaabbbaababbaabaaabab", want: true},
				{input: "aabaaaaabbaaaaaabbababbbbabaaaaabbaaaabb", want: true},
				{input: "bbbbababaaabbaaaaababbaa", want: true},
				{input: "baabaaabbbbbababababaabbaaabbabbaabbbaab", want: true},
				{input: "bbaabbabbbabbbaababbbbbabaabaabbbababababaaabaaa", want: true},
				{input: "baabbbbbaaaabbbabbbbbbbb", want: true},
				{input: "bbabbaabbbabbaaabbbaabaabaaabbbbaababaaa", want: true},
				{input: "babbbaababbbabbababaabbb", want: true},
				{input: "aabbbbbabbbbaaaabbbaabababababbb", want: false},
				{input: "aabbabaababababababbaaabaaabaabb", want: true},
				{input: "aabababbaaaaaaaababbbbaaabaaaaaa", want: true},
				{input: "abbbababaaabbaabababababbaaabbbbaaabaabb", want: true},
				{input: "baabbabaaabaaaaabbbbbaabababaaaa", want: true},
				{input: "abbbbabbbababbababbaabbbbaaaabba", want: false},
				{input: "abababbababaaabbabaabbbb", want: true},
				{input: "aaaabbbaaaaaabaabaaabbba", want: true},
				{input: "bbaabaababaaaabbaaaaaabb", want: true},
				{input: "aaabbabbaabaabbbaabbaaba", want: true},
				{input: "aaaaabaabbaabaababbabaaa", want: true},
				{input: "bbabbbbabbbaabbbabbbbaab", want: false},
				{input: "aaabbabbbaaabbbbbaabaabbbabababbaaaaaababbbbaabb", want: true},
				{input: "abaabbabbabaaabababaababaabbabbbabbbbaaaaabbbbaabbaaaaababbbabbaabbbbbabaabaabbabbbbbaabaaaabbab", want: false},
				{input: "bbbaababaaaabababaaaaaab", want: true},
				{input: "bbbbabbbaaababbbaabbbbbb", want: false},
				{input: "babbbaabaababbbaabbbbbaa", want: true},
				{input: "abababbabbbabbabbbbabaaa", want: true},
				{input: "abaabaaaaabaabbabaaabbbbbbababab", want: true},
				{input: "abababbaaabababbbababaaa", want: true},
				{input: "baaabbabbbbbbabababbaaababbbbabbbaababbbaabbbbabbbaaabbabbbbbbab", want: true},
				{input: "aababbbaabababaaaaaaabab", want: true},
				{input: "baaabbababbaaaababbabbbabaaabaaabaabbbbaaabbabaabbbaabbbabbabbabaabbaaab", want: false},
				{input: "baaaabaabbababbbbbbbbababaaabaab", want: true},
				{input: "bbabbaababbabaabaaabaaabaaaabbaaabbbbaab", want: true},
				{input: "bbbaaaaaabbaaaaabaaaaaaa", want: true},
				{input: "bbabbbaababbbaaaababababbbaabaabbbbbababbaaabbbaabbaaaabbaaaaaaa", want: true},
				{input: "abbbbabbaabbabbbaaaaabba", want: true},
				{input: "babbababbaaabbabbabbaabaaaaaaaba", want: true},
				{input: "bbbbababbababbbbabbababbaaababab", want: false},
				{input: "abbaaaababbabbbbbabbaaabaababaab", want: false},
				{input: "aabbbbbbabaabababbbabaaa", want: true},
				{input: "aaaaaaaababaaabaabaabbaaabbabbbaabaaaaaabbaabbba", want: true},
				{input: "abbbababaaaaabaaaababbbaaaabbaaa", want: false},
				{input: "bbbbbabbaabaaaaaaabaabbaaaaabbaa", want: true},
				{input: "ababbabababbbaabababbbaaabaabbbb", want: true},
				{input: "ababaabaabbabbbabbbabbbabbaaaababaabbaaa", want: true},
				{input: "ababaabaaaababbbbaaaabaabababbaaabbababb", want: true},
				{input: "aaabbbaabaabbbbbbaaababbaaaabbbabbbbbbbb", want: true},
				{input: "aaababbbaaaabaabbababaab", want: true},
				{input: "aabbbabaababbbabbaaaabab", want: true},
				{input: "abaabbbbbbabaabaaababababbbabaabbaabbaabaabababbabbaaaababaaaaaa", want: false},
				{input: "abbaaaababaaaabaabbbbbabbbaaabaaaabbabaa", want: false},
				{input: "babaaaaabbbaabababaaabbb", want: true},
				{input: "abbbbbbaabaabaaabbaaaaaabbabbbaabbabbbbbaabbbbababbababb", want: true},
				{input: "baabbababbbabbababbbbbaa", want: true},
				{input: "bbabaababbbabbabaabbbaab", want: true},
				{input: "ababbbabbbbbabaabaaaaabb", want: true},
				{input: "babbbbbbbaaaabbbabbbbaba", want: true},
				{input: "babbabaabaaabbababaababaababaaab", want: true},
				{input: "aaaababaaaababaaabbbabbaabbaaaabaaaabbab", want: true},
				{input: "abbaabbbbbabbabbababbbbbbbbabbaabaaaababbbbaabbabaaaabbbbabaaaabaaaabbab", want: false},
				{input: "baabbbbabaabbbbabaaabaaa", want: true},
				{input: "aaabbaaaaaabbabaabaaaaab", want: true},
				{input: "abbabaabbaaababbaabbabab", want: true},
				{input: "aabaabbbbaababbabbbbbaaabbbaaabb", want: true},
				{input: "aaaaaaaaaabbabbbaabaaabbabaaabababbbaababbaaabababbbbaaaaaabbbababaaaaaa", want: false},
				{input: "babbabababaaaababaaaabba", want: true},
				{input: "abbaaaaaaaabbaaabbbaabaaabaaaabbabaabaaabbbaabbbbbbaabbbbbaabababababaab", want: true},
				{input: "bbabaababaabbabbbbaaaaba", want: true},
				{input: "bbabbbaaaabaaabbbbbabbbaaabbbbba", want: true},
				{input: "babbbaaaaabbaaaababbbabb", want: true},
				{input: "bababbabbbaabaabbbbaaaaabaabbbab", want: true},
				{input: "bbbaaaaabababbaabaaaaaab", want: true},
				{input: "babababbbaabaaaaaaaabbbaabbbabbb", want: false},
				{input: "aaaaabaabbabbababbaabbba", want: true},
				{input: "aabababbabbabbaabbbaabbb", want: true},
				{input: "baaababbaabbaaaaaabbbabb", want: true},
				{input: "bbaababbaaabbbaababababbaabbaaabaaababab", want: true},
				{input: "baaaabaaababababaabbabbbabababbaaababbbbbbbaabba", want: true},
				{input: "babbbbabbbabbababaabaaabbbbaaaabababaaab", want: false},
				{input: "baaaaabaaabbbbaaabbaabbaabaabbbabababbabbaaabaaaaaabaaababaabbabbabaaaaaaaabbbbb", want: false},
				{input: "babbbaaaabbbbbbbaaaababbaabbbbbbbbbaaaabbbabbbbabaababaa", want: true},
				{input: "baabbbbbabababbaabababaabaabaabaaababbbbbbaabbaa", want: true},
				{input: "babaaababaaaaabaaabaabbabaaabbabbaaaabaabbbaabbbbbabaaabaaaaabbabbbabaab", want: true},
				{input: "abbabaaababaabaaabaaabaaababbbaababbababbaaabaaababbaaaa", want: false},
				{input: "ababaabaabbababaaaabbbbb", want: true},
				{input: "baababbabaabbbbbbbbaabaaababaaabbbbbbbaa", want: true},
				{input: "aabbaaabbbbababbababbaaa", want: false},
				{input: "babaabbabbbbbabbabbbbaba", want: true},
				{input: "abbbabbbbaaababbabaabbaabbbabaaa", want: true},
				{input: "babbbaaabaaaabaaaaabaaabbaaabbbbbabbaabaabaaabba", want: true},
				{input: "bbbbabbbbabbaababbabbbbb", want: true},
				{input: "bbbbaaaabaabbbabbbbabbaaaabbbaab", want: false},
				{input: "babbbbbababababaaaaabaaa", want: true},
				{input: "babbaabbbabaabbababaaaab", want: true},
				{input: "abbbabbabbababbbaabbbbaa", want: true},
				{input: "aaabbaababbbabbbbbaabaaa", want: true},
				{input: "babbaabaabaabaaaaaaaaaaabababbba", want: true},
				{input: "aabaaaababaaaabaababbbababbbababaabababa", want: true},
				{input: "bbbabbbbaaababbaabbbaaaabbbbbaabbabbbbbaaaabbbbaabbbaabb", want: true},
				{input: "abbabababbabbaaaabaabbba", want: true},
				{input: "abbaaaabbaaaabbabbbababaabbbabaa", want: false},
				{input: "abbaaabbbbaaababbbbaaaabbabbbbbabbbababbaababbab", want: true},
				{input: "baaababbababaababbbbabaaaabbababbaaabaaa", want: true},
				{input: "babbaaabbaabbbbbaabaaaaababbabaabaaabaabaabbbabbbabaabaa", want: true},
				{input: "aaababbbaaaababaababbaab", want: false},
				{input: "baaaabbbbaabbbaaabbaabbb", want: true},
				{input: "babbbaabaabbabababaaaaabaabbaabababaabbb", want: false},
				{input: "abbabbbbabababbababbaabaaaaaaaababbaaabbabbbbbaabbbabbabbbbababb", want: false},
				{input: "baaabbbbabbbaaaabbbaabba", want: true},
				{input: "abababaabaabaabbbbbabbbaaaabbababaabbbaabbababab", want: true},
				{input: "aaaabaababababbaaababbbabbabbaabaabbbbabbbbbbbaaabaaaaaa", want: true},
				{input: "aabaaabababbbaabbbbbbbaa", want: true},
				{input: "aabaaaabbaabaaaaaaaaabba", want: true},
				{input: "babababbaabbbaaaabbaaaba", want: true},
				{input: "abbabbbaaaababaaaabaaaaaaabbbbbbabaaabbb", want: true},
				{input: "bbbaaabaaabaababbbbaabba", want: false},
				{input: "bbabaababbbbbabbaaaababaaabaaaaaabbbbaaabbaabaaa", want: true},
				{input: "aaaababbbababbababbbbbbaaaabaaaaabbaaabaabbbbbaabababaab", want: true},
				{input: "baabbbbbaabaaaababbabbaaaaaabaaa", want: true},
				{input: "bbbbbaabbbbbabaababbbaaabababbbbbbbaaaaaabbbbaba", want: true},
				{input: "ababbaabaabbaabbaaaabbbb", want: true},
				{input: "bbbbbaabaabbbbbbbaaaaaaa", want: true},
				{input: "bbbbbaaabbbbabbbaabaaabbbabaabbb", want: true},
				{input: "bbbbbaabaaababbaaaabbaaabbbbababbabaabbabbbaaabbaaaaabbb", want: true},
				{input: "baabbbaabaabbababbababbabaaaabab", want: true},
				{input: "abaababbabbabbaaababbbba", want: true},
				{input: "aaabbaababbabababababaaabbabbbbb", want: false},
				{input: "aaababbbbabbabaaabaabaaabbbbaaba", want: true},
				{input: "baaababbbabbaaabbaabaaaabbbababb", want: true},
				{input: "abbbbbbaabbbabbaaabaaaabbbababbbaaabbbab", want: true},
				{input: "bbbbbababbbaababbababaab", want: true},
				{input: "aaaababababbbaaaabababbb", want: true},
				{input: "bbabbaababbababaaabaaababbbbababbbbbbbabbbaaabbb", want: true},
				{input: "abbbbbbbaabaabbaaabbbaab", want: true},
				{input: "bbbaababbbbbbaaaaaaabbab", want: true},
				{input: "babbbbbaaaaababbaaaaaabb", want: true},
				{input: "baabbbaabaabbababbabbabb", want: true},
				{input: "baabbababbbaababaabbabba", want: true},
				{input: "baababbabaaabbabbaaababbbabbbbbbbaababbbbabbbabbbababaab", want: true},
				{input: "bbaaabaaaaababbaaaabbbab", want: true},
				{input: "babaabbaabbbbbbbbabaabbb", want: true},
				{input: "ababaabaaaabbbaaabababaaaabaaabbbaaaaabb", want: true},
				{input: "baabbabbaabbaabbaaaabababbabaaab", want: true},
				{input: "aabaabbbaaababbbabbbbaab", want: true},
				{input: "bbbbbaaaaaabbabababbbbaaaabbbabb", want: true},
				{input: "baaabaabbaaabbbabaabaaababaabababbbababababbaaababaabaabbbbabbabaaabbabbaabbaaabaaabaaab", want: false},
				{input: "aabbbbbbaabaaabbbbabbaaabaaaaabaabbbaaaababaabaa", want: true},
				{input: "aaaabaabbababbabbbbabbbbaabbbababbbaaabaababaaaaabbabbab", want: true},
				{input: "babaababaaaabaabbaabaabbbaabbababbabbbbb", want: true},
				{input: "bbbaababbbbaabaaabbbabbbabbaaaba", want: true},
				{input: "baaaabbabbbbaaaaaaaaabbbbbabababbbbababaaababbbabbababababbbbbba", want: false},
				{input: "abbbabaaabaabbbaaabaabaabbbbbbab", want: false},
				{input: "babaaaaabaabaabaaaabaabb", want: true},
				{input: "aabababbabaabaaaaaaabbbabbaabbabaaaabbabbaaabbba", want: true},
				{input: "ababbbabbbbbbaaaaaabbaababbbaaaaaaaaabba", want: true},
				{input: "baabbabbbbabbaababbabbaaabaabbba", want: true},
				{input: "bbaaababbabbabbabbabbaabaaaaaababaabaaabaababaaa", want: false},
				{input: "baabbbbbbbbaabaaabbabaaa", want: true},
				{input: "abbabababaaabbabbaaaabab", want: true},
				{input: "ababbababaabaaabaabbbbbbbbbabaab", want: true},
				{input: "baabababbaaaabbababbaaaaabaabbaa", want: false},
				{input: "abbaaabbabbabbabaaaaabbbbabbbbaaababbbbbaababbabbaababbaabbbabba", want: false},
				{input: "abbbbababbabaabaabbaaaabbaabbabaaabbaababaaabaababaaaabbabababba", want: false},
				{input: "babbaaabbbabbabaaaabbbab", want: true},
				{input: "aabbbaaaabbbbabbaaabbbbb", want: true},
				{input: "baababbbbaaabbababbbabbbbbaaabaaaabbaaaaaaaabbab", want: true},
				{input: "babaabababababbababbbbbaabbabaaa", want: true},
				{input: "babaaabaaaabbabbaabaaababbaabaabbaababbbabaabbbabbbbabbaabbaabaa", want: true},
				{input: "baababbabababbabbbabbaabbaabbbaabbbababb", want: true},
				{input: "baabaabbababaabbaabbaaaaaaaaabba", want: true},
				{input: "aaaababbbabbaababbbbaaba", want: true},
				{input: "bbbabbbaaaaababbaabbbbaa", want: true},
				{input: "abaaaabaaaaaaaaaaaabbaaaabaabbab", want: true},
				{input: "ababbaabbabbaaaabbbbaaab", want: false},
				{input: "baaabbbbabbbaabababaabababaabbbb", want: true},
				{input: "baabaabaaabaaabbbbbaabaaaabaababaabbbbba", want: true},
				{input: "bbbbabaababbbaabaaaaaabbbaaababa", want: false},
				{input: "abbabababaabbabbababbabb", want: true},
				{input: "babababababaaaaaabbbbbaa", want: true},
				{input: "aabbbbbbbabaaaaabbbaaaaaabababbbabbbaabbababbaaa", want: false},
				{input: "babababaabaababaababaaab", want: true},
				{input: "baababbabaabbbbaaaabbbaabaaabbabababaababaaabaabababbbbbbbabababbaaabbaa", want: true},
				{input: "abbbaabaaabbbabaaaabbbbb", want: true},
				{input: "bbabbabaabbabbbaaabbabbbaababbababbabaaa", want: true},
				{input: "abbaababaaababbbabbbbbab", want: true},
				{input: "aaababbababaaabbabbababb", want: true},
				{input: "baaaaabababaaabbbaabbbaabaaabaaa", want: true},
				{input: "aabaaaabbbbbababaaababbb", want: false},
				{input: "abaaaabbbabbabbaabbbbbbbabbaabbb", want: true},
				{input: "bababaaababbbbaaaaaabababaaaababbaabbbabbaaabbabaabaaaaababaaaabaabaabbabbbaaabbaababaab", want: false},
				{input: "aabbabbbabbaaaaaaaababab", want: true},
				{input: "bbbaaaaaababbaabababbbba", want: true},
				{input: "ababababbbababbbaaabbaabbababbbabbaabbaa", want: true},
				{input: "aabbabaabaaabaabaaabaabaaaabaabbbbababbaaaababababbbbbabbbaabaaababbaabababaaaabbaaaaaba", want: false},
				{input: "abbbbabbbbaaaaaabbaabaaa", want: true},
				{input: "aaaababbbabaaabbbabaababaaabaaabaaaaabbb", want: true},
				{input: "ababbbaaabbabbaabbaaabbb", want: true},
				{input: "abaaaabbbaabbbaaaaabaaabbbabbbba", want: true},
				{input: "aaabaaaaaaabbabaabbabbaababbbbbaabaabbbb", want: true},
				{input: "aaabbabbbabbbaababaababbaaaaabbbaababbbb", want: true},
				{input: "aabaabaabaaaabbabaaabbaaabbabaaaaabbabbbbbabaaaabbbababbaabaabbb", want: false},
				{input: "abaabbaababbaaabbabaaabbbabaabbabbabbabaabbbbbabaababbaa", want: true},
				{input: "ababbbabbbbabbbbbaaaabbbabbabbbaaaaaaaab", want: true},
				{input: "abbbabbabaaabbababbbababaaabbaabaaaaabba", want: true},
				{input: "abaaaabababaaaaabbaabaabaababaaa", want: true},
				{input: "bbbbbbabbabbbbaaaaabbbabbbaaaabaaabaabab", want: false},
				{input: "bbbaaaaaabbbbbbbaabababa", want: true},
				{input: "baabaaaabbbabbbaabababbb", want: true},
				{input: "aabbbabaaaaaabaabbbabbaa", want: true},
				{input: "babaaabbaaaaabaaabbbbbbbbabaaabbaaaaabab", want: true},
				{input: "bababbbbbaabbabbbbaaabbb", want: true},
				{input: "bbaabbbaabbabbbbaabbbabb", want: false},
				{input: "abbabaabbabbaabaaababaaa", want: true},
				{input: "bababbaabaabaabbabbabbab", want: true},
				{input: "bbbaababbabbabaabaabbbbabaaaaabbbbbbaaab", want: true},
				{input: "bbbaababbabbbbaabababbba", want: true},
				{input: "babbaabbbabbabaaaabbabbbbabaaaabbbbababb", want: true},
				{input: "bbaabaababaabaaaababaaababaaabbaababbbbb", want: false},
				{input: "abbbabbbaababaaaaaabbabbabababaaaaababaaaaababbabbaababb", want: false},
				{input: "abbaaabbbaabbabbabaabbaaaababbbabbaabaabababbbabaaabbbab", want: true},
				{input: "abbbaaaaaabbbaaabbaaabbb", want: true},
				{input: "bbbbbabbabbabbaaabbabbbb", want: true},
				{input: "baabbabaaaaabababaaaaaab", want: true},
				{input: "aaaababbbbbabbbaaaababaabababbbb", want: false},
				{input: "abbbabaabbbababbbbabbbaaaaaaabaaaaaaabbbaaababab", want: false},
				{input: "baaabbbbaaabbaabbaaabbababbaababbbbaaaba", want: true},
				{input: "bbaababbbbbbbababaaababbabbabbbaaabbbabaabbbabbbbaaabaabaaabaaba", want: true},
				{input: "aaabaaaabbbbabbbbabbbabb", want: true},
				{input: "bbabbaababaababababbabbb", want: true},
				{input: "babbaaababbbbabbabbbaaabaabbabba", want: false},
				{input: "bbabbaabbabbabaababaaaaaaababbabbaaabbaababbbbbaababbbabaababbabbbabbbaabbbabbbbabaabbab", want: false},
				{input: "baabaaaaabaaaabbabbbbbbbaabbbaaabaaabbabbabbabbaaaaaaababaaababaaaaaabbb", want: true},
				{input: "bbaabbabbbaaabaabbaababa", want: true},
				{input: "aababbbabbbaabaaaaabbbab", want: true},
				{input: "baabbbbaabbabbaabbaaaabb", want: true},
				{input: "bbabbaabbaaaabaaaaaabbbb", want: true},
				{input: "baabaabaaabaabbaabababbb", want: true},
				{input: "abaabbaabbaabaabbbaabbabaaabbbaaaaaaabbb", want: true},
				{input: "bbbbbababbaaababbaabbaaa", want: true},
				{input: "bbaabbabbbabbaaabaabbbab", want: true},
				{input: "bbbaaaaaabbbbbbbaabbabaa", want: false},
				{input: "bbaaababbbabaabbaabbaaaaaaabbbbbbaaababaabbbbbbbbabaabaaaabbabab", want: false},
				{input: "aabbaabbbabbaaabaabbaaaabbababab", want: true},
				{input: "abbbabbaaaababbaabbaaaaa", want: false},
				{input: "aaabbabbbbaabaabbbabbaaaabbaaabbbabbbaba", want: true},
				{input: "abaabaaababbababaaababbbaabbbabb", want: true},
				{input: "abaaaabababbbbbbaaabaaaaabababbaaabbbbab", want: true},
				{input: "abbaabbbbbabbbbabbbaaababbabaaabbbabbbab", want: false},
				{input: "babbbbbbbabaabbabaababbaabaabaaaabbbabaababbbbab", want: true},
				{input: "bbbabbbbaabbaaaaabbaabaa", want: true},
				{input: "bbbbbaaababababbbaaababa", want: true},
				{input: "baabbbaabaabbababbbaababbbababbbabaabbbb", want: true},
				{input: "bbaababbbabaaabbabbbaaab", want: true},
				{input: "baabaaaaabbaaaaabbbaaaabbabbabbaaabbbaaaaabaabbbbbbbaaba", want: true},
				{input: "abbbababaaaaabaaababbabb", want: true},
				{input: "aaaaabaababbaaabaaaababbbaaabbbbababaaaa", want: true},
				{input: "ababbaababbabbbababbabbabbabbaababaaaaabbbbbaaaabbbaaaba", want: true},
				{input: "baaabaaabbbbabaaaababbaabbbaaabaababbabbaaabaaba", want: false},
				{input: "bababbaaababababaabbabbbaabaabaaabaaabbaabbbaaaaabbbabaa", want: false},
				{input: "abbaaabbabbaababbbaaaaaabbaaaabb", want: true},
				{input: "bbaabaabbbbaaaaabababababbabbbaaaaabbbba", want: true},
				{input: "bbaababbabbababaabbbaababbabbabbbbabaaab", want: true},
				{input: "abababaaabbbaaaabababbaaabbbaaababaaaaab", want: true},
				{input: "abbabaababbbbabbbbaabbbb", want: true},
				{input: "ababbaabbabbabababaaabbb", want: true},
				{input: "aababbbabababaababbbbbbaababbabbaababbbbbbbbaaaababbaabbbaaaaabb", want: false},
				{input: "abbbaaaaaabababbababbbba", want: true},
				{input: "babbabaaaaabbbaabaaabbaa", want: true},
				{input: "aabaaababaabbbaaaabaaababaaababbabbbaaaaaaaabbaa", want: true},
				{input: "bbaabbabbbabbabaaabbaaba", want: true},
				{input: "bababbaabbbaababbaaaabaaabbbbaab", want: true},
				{input: "bbbabbbabbbabbababbbaaab", want: true},
				{input: "abbbbbbbaabbabbbaaaabaabaabbaaabaaaabbbb", want: true},
				{input: "bbbbbabbbaababbbaabbaaba", want: true},
				{input: "ababababababababababbabb", want: true},
				{input: "baaaaaaabbabbaababaaabbb", want: false},
				{input: "bababbaaabbabababababbabaabaabbabbaababaababbbbb", want: true},
				{input: "bbabbaaabbbbaabaababababaabbbbabbabaabbbbaabbbaabbaaaababaabaabb", want: false},
				{input: "abbababaabaaaabbbabaaaab", want: true},
				{input: "bbabaabababbaabbbabbbbbbabbbbaabaabaabaa", want: true},
				{input: "bababbaaaabaaaaabbbbaabb", want: true},
				{input: "bbaabbabaabaabbbbabaabbaababaaababbaaaab", want: true},
				{input: "babaaabaaabaaaabababaabababbbaba", want: true},
				{input: "babbbbbaabababbaaaabbaabbabbabaabbaabbbb", want: true},
				{input: "abbababaabababaababaaababbbabbaa", want: true},
				{input: "aabaaaaaabbabbaabbabaababaababbaabaaabbb", want: true},
				{input: "abaabbaabbbbbaaaabbaabba", want: true},
				{input: "babaabbabaabbbbbbbabbbaababbbaabbbbababbaabbbaaabababbbbbaaababaabbbabbabbaaaabbaababaabaaaabbba", want: false},
				{input: "aaaabbbabbaaababaaabbaaaabababaababbbbababbaabbb", want: true},
				{input: "baabbabaabbaababaabbabab", want: true},
				{input: "ababaabbaabaaabaabbababb", want: true},
				{input: "aabbbababbaabbabaaaaabaa", want: false},
				{input: "ababaababbbabbbbbaaaabab", want: true},
				{input: "ababaababaaaaababbbabbbaabbbabaa", want: true},
				{input: "abaabbaaabbabababbbbabba", want: true},
				{input: "babbbbbabbaaaaaaaaaaabab", want: true},
				{input: "bbabbababbbabbbbababbbbb", want: true},
				{input: "abaababbabbaaabbbbbbababbbbbaaaa", want: true},
				{input: "abaaaabbbababbbbaababbbb", want: true},
				{input: "baabaababababbbbababbabb", want: true},
				{input: "baaaabaaaaabbabbabbabababaabbababbbbabaaabaaababbabbaaaa", want: true},
				{input: "aaaaaaaabbbabaaabbabbabaaabbbbaaabaaababababbabbabababab", want: false},
				{input: "bbbaaaabaaabaaaaaabaabbbbababaab", want: true},
				{input: "baabbbbabaaaaabaabbbaabb", want: true},
				{input: "abaaaabaabbaaaaaabaababbbaaabbba", want: true},
				{input: "ababbbaabbbaabaaaaababab", want: true},
				{input: "aaababbabbbbbabbabbbaaaabababaab", want: true},
				{input: "bbbbabbbbababbabaabbbbba", want: true},
				{input: "baaabbbbbbbbbaaabbaaabaaabaaabbaaababbab", want: true},
				{input: "bbabbaabababbbbbbbbaaabbabbbaaba", want: false},
				{input: "aaabbababaabaaabbaababbbbbaabbababbaaabbbbabbabbaabbbbab", want: true},
				{input: "abbaaaaabbabbaaaabbababb", want: true},
				{input: "baabaabbbaabbabababbaaabbaaaaababaaaabbabbbbbbaa", want: true},
				{input: "babbaabaaabababbbabbabaaabaaaaabbbaaabbb", want: true},
				{input: "babababbaabbaabbbbbbaaab", want: true},
				{input: "babaaababbbaabaaaaaabaabbbbaaaabababbaaa", want: true},
				{input: "aaabbbbbbbabababaabbabba", want: false},
				{input: "baaabbaaaaabbbbaaababbaaabbaaaaabbabbbbbabbbabbbbbbaaaaabbaaaababaaabbbbbaabbaababbbbbbababbaaaa", want: false},
				{input: "ababbababaabbabaababbbababaababbabbbaaaabbbbbbaaabbababb", want: true},
				{input: "babababababababaaaaabbab", want: true},
				{input: "aaabbaaaabbbbabbabaaabbb", want: true},
				{input: "babbbaaabababbaabaabaabaabbaababaaaabaaaababaaab", want: true},
				{input: "babaaaaaabbbbabbbbaabbba", want: true},
				{input: "bbabbaabaabbbaaaaabaaabaabbbababaabbaabaababaaaaababbbba", want: true},
				{input: "aabbbabaabbabbbababbaaaa", want: true},
				{input: "baaaabaababbabaabbbaabbb", want: true},
				{input: "aaabbabaaaabaaabaabbaaaabbaabbaa", want: true},
				{input: "abaabaaaabbabbaabbaababbabababbabbbbaabbbbaabbba", want: true},
				{input: "bbbaaaaabbabbabaabaaabaa", want: true},
				{input: "ababbbabbabbaababbaabbaa", want: true},
				{input: "aaabbaaaababbbabbaabbaaa", want: true},
				{input: "aaaaabaaabbabbaaabbbbaab", want: true},
				{input: "bbbaaaababaabaaabbbabbbabaabaaaabaabbbaaabbabaabaaaabbbb", want: true},
				{input: "babaaabababbbbbaaaaabbaa", want: true},
				{input: "baabaabbbabaabaabbaaaaab", want: false},
				{input: "baababbbbaaabbabaababbbb", want: true},
				{input: "bbaababbbbababbabbabbbbb", want: true},
				{input: "abbaababaabaabbaabbbbbbbbbaabbbbbbaababa", want: true},
				{input: "babaaaaaaaababbaabaaabab", want: true},
				{input: "babaaaaabbaabbaabaabbaabbbaabaaabbbbaabbbbbaabba", want: false},
				{input: "bbbaaabaaabbbabbabbaabbb", want: false},
				{input: "bbbbabababbaaaaaaabbbaaabbbbabaabbaaaaaabbbbaaaa", want: true},
				{input: "bbbaaaaaabaabaaabaaababa", want: true},
				{input: "aaabbababaaabbabbabaaaaaaaababababbbbaab", want: true},
				{input: "babbbbbabababbababaaabbb", want: true},
				{input: "aabababbaabbabbbbbbbbbba", want: true},
				{input: "abbabbaaabaababbbabbabbaaaaabaabaabbbbba", want: true},
				{input: "babbabbaabababbabababbbbaaababaaabbaaabbaabaabaa", want: true},
				{input: "aaaaaaaabbbabbbaabaaabba", want: true},
				{input: "baaaabaaabbbbbbaaabaabbbbbbbaaaa", want: true},
				{input: "abbbaaaabababaaabbbbbabbabaaabaaaaababbbabaababaabaaaaaa", want: false},
				{input: "abaababbabbbbbbaaabbabbbabbaaaab", want: true},
				{input: "abbabbbababbaaabbbabaaaabaababaaabbaabba", want: true},
				{input: "aaaabaabbbababbbbabbbbaabbbabbababaaaaab", want: true},
				{input: "abbaaabbabaababbbaabaababaaababa", want: true},
				{input: "abababababbaaabbbaaabbababaabaab", want: true},
				{input: "baaabbabaabaabbaaabababa", want: true},
				{input: "bbaaabaaaaaaabaababbaabb", want: false},
				{input: "ababbabaaabbabaaaabababa", want: true},
				{input: "babbbbaabbbbbaabbbaababa", want: true},
				{input: "babaaaababaabbababbabbbaabaaabababbabbaaaabbaabb", want: false},
				{input: "baaababbaaabaaabaabbabbbbaaaaaab", want: true},
				{input: "abaabbaabbabbaabaabababbabbabbbb", want: true},
				{input: "bbbaababaababbbabbababab", want: true},
				{input: "baababbabaaaabaaabababbababaaaab", want: true},
				{input: "babbaababbabaaaaababbaaa", want: true},
				{input: "aababbbaaabababbaabaabab", want: true},
				{input: "bbaabbabaabbbbbbbbababbbaaaabbbabbbbaaba", want: true},
				{input: "bbaaababbbaaabaabbbaaabaababbbbababbbabbababbbbaabaabbba", want: false},
				{input: "bbabaaaaaabbbababbaaabbb", want: true},
				{input: "baaaabaabaabbababaabaaababbbaabbbbabbaabbbbabbabaaababaaaabbaaaaaaaabbabaabbbabaabbabbaa", want: false},
				{input: "abaaaabbaabbabaaaabbbababbabaaaaaabbaaba", want: true},
				{input: "baaaaaabbbabbbbaabbbbbbbbbabaabbbabbabababaabababbbbaaabaaaabbbababbbbaa", want: false},
				{input: "aaaaaaaaaabbbabaaabbaaab", want: true},
				{input: "aababbbababaabbaaaabbbababbbaabb", want: false},
				{input: "abbbbabbaaabbbaaababaabbbabababa", want: false},
				{input: "aaaaabaabaaaabaaabbaabaa", want: true},
				{input: "bababbabbabaababbabbbabb", want: true},
				{input: "abbbbabbbaabbbabbbbaabaabbbaabbaaaaababaaaaaaaaababaaaba", want: false},
				{input: "aabaaababbbaabaabaabaaaabbbbaaababbbbaba", want: true},
				{input: "abbabaabbbaaababaaabaaba", want: true},
				{input: "bbaaababbbbbbaababbbabaa", want: true},
				{input: "bbabaaaababbbaaaabaaaaaa", want: true},
				{input: "aaabbaaabbabaababaaaabba", want: true},
				{input: "baabbabaaabbaaaaabbbbaba", want: true},
				{input: "baabaabababbaabbbbababaa", want: true},
				{input: "aaaabaabbbaaababaabbaabbabbbaaaaabaabaab", want: true},
				{input: "aaababbbaabaaaabbaaaabbbbabbbbba", want: false},
				{input: "aaabbbaababbaababbaaaaba", want: true},
				{input: "bbbabbbababbbaabbbaababa", want: true},
				{input: "abbbaaaabbabbbaaabbaabaa", want: true},
				{input: "aaaaaabbbbabbaaaabbabbbabaabbbabbbaaabaabaaaabaa", want: false},
				{input: "abababaaaaaaaaaaabbbaababaaaabbabbaabbabbabaabaaaabaabaababaabbabaabbbbb", want: false},
				{input: "ababbbaaabaabbaaabaababaabbbbbaa", want: true},
				{input: "abbabbbaababbababbbbbabaaabaabbabaabbabbbbaaaabaabaaabaa", want: true},
				{input: "ababbaabababbbabbbbbaaab", want: true},
				{input: "babbabaababaaabbbaabaabb", want: false},
				{input: "bbababbbaaabbaabbabbabaaaabaabaa", want: true},
				{input: "abaababbbaabbababaaababbbabaababbaaaaabaabbabbbb", want: true},
				{input: "ababababaaababaabbaaaabb", want: true},
				{input: "bbbaaaaaababbaababaabbba", want: true},
				{input: "babbbaababbbabbabbabaababaababbabbaababa", want: true},
				{input: "baabaabbbbaaaaaabbbaaabb", want: true},
				{input: "abbbaababbbbbabababbaabaaaaaabaaabbaaaaaabbbbaabaabbbbaaaabbbbabaababaab", want: true},
				{input: "ababaabbaabababbbbabbaabaaababaabaaaaababaaaabba", want: true},
				{input: "ababbbbbaabbaababababaababaaaaaaabbaaaaabbabbbaa", want: false},
				{input: "abbaaabbabaaaabbbbbabbbbbabbaabbbbbaaaaaabbbabbbbbbaabba", want: true},
				{input: "aaababbaaaaabaabbbaaababaaaabbbb", want: true},
				{input: "aabaaababbbbbbabaaabbabaabbaaaaabbbbbbbbababababbbaababbbabbabab", want: false},
				{input: "bbbaababbaaabbaabbbbbbaaabaaaaabaabbaababbaaaaab", want: false},
				{input: "aaaabbbaababbaabbabaabbababaaabbbaabbaab", want: true},
				{input: "bbbabababbababababbaabaa", want: false},
				{input: "bbbbabaabbaababbaaaabbbaabbbbbab", want: true},
				{input: "aaabbaaaaaaabbbaabbbbbbaabaaaabababbbaaabbaababbbaaaaaaaababbbbabababaaa", want: true},
				{input: "aaaaabbababbababbbababbbbaaababbabaabbaaaababbaabbaabbaa", want: false},
				{input: "bbabbabaaaaaabaabababbbbaaabbbba", want: true},
				{input: "ababbbaabbababbaaaaaaaab", want: true},
				{input: "babaaabbbaabbabaaaabaabb", want: true},
				{input: "babbababbbbbabaabababaab", want: true},
				{input: "bababbabbbaabaabbbbabaab", want: true},
				{input: "abbbaabaaabbbbbbaabbbbbbaabaaabbbbbbbaaaababbaaaaababaaabaaabaaa", want: true},
				{input: "abaabaaaabaababababaaabaaaabbbaabbabaaab", want: true},
				{input: "ababbbabaaaaaaaababbbbab", want: true},
				{input: "bbabbbbaabbbbabaaaaaabbbbababbaaabbbbbbbbbaabbbabbaaababababbbbbabbaabbabbabaaaabbbabbba", want: false},
				{input: "abaaaabbaaabbaabaaabaaaabbbabbbbababbbaabaabbbab", want: true},
				{input: "aabbbbbbbabbaababaabbababaabbbba", want: false},
				{input: "baaaabbbbababbabbbaabbba", want: true},
				{input: "abbbaaaaababbbababbabaaa", want: true},
				{input: "bbbabbbaaaababbaabaabbaaabaababaabbabababbaaabbaaaaaaabbabaabbabbbbaabbb", want: true},
			},
		},
	}
	for i, tt := range tests {
		t.Run(fmt.Sprintf("Test_%d", i), func(t *testing.T) {
			p := NewPDA(tt.startSymbol)
			p.AddRules(tt.rules)

			for _, inputResult := range tt.inputResults {
				if got := p.Match(inputResult.input); got != inputResult.want {
					t.Errorf("Match() = %v, want %v - for %v", got, inputResult.want, inputResult.input)
				}
			}
		})
	}
}
